sonar:
    num_samples: 3200 
    slant_range: 50.0

simulator:
    separate_inputs: true                                  
    publish_rate: 20                                   
    nav_topic_name: "/girona500/navigator/navigation"    
    pings_topic_name: "/pings"
    ping_info_topic_name: "/ping_info"
    xtf_file: "st_feliu_221028151800.xtf" 
    ping_start: 0                                
    nav_rosbag_file: "rosbag_nav_only_2023-11-15-15-11-13.bag"   
    robot_dae_file: "girona1000.dae"
    robot_mesh_rotation_offset: [90.0, 0.0, -90.0]

undistortion:
    correct_waterfall: true
    max_pings: 256
    interpolation_window: 200

behaviour:
    num_steps: 50
    step_rate: 5
    slow_down_rate: 0.3 
    min_confidence: 0.85 

prediction:
    patch_shape: 256
    stride: 128
    encoder: 'sima_mini'
    decoder: 'atrous'

visualisation:
    resolution: 0.3 
    publish_prediction: true
    publish_grid_cells: true
    publish_swath_lines: true
    publish_undistortion: true
    publish_waterfall: true
